name: try-jupyter
channels:
- conda-forge
dependencies:
- python=3.10
- mamba
- pydata-sphinx-theme
- myst-parser
- bqplot
- ipycanvas >=0.9.1
- ipyleaflet
- ipympl>=0.8.2
- ipywidgets>=8,<9
- jupyterlab>=3.5.2,<4
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlab-fasta>=3,<4
- jupyterlab-geojson>=3,<4
- jupyterlab-tour
- jupyterlab-night
- plotly>=5,<6
